config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root to: 'welcome#index'
  get 'welcome/index'

  resources :notifications

  namespace :api do 
    namespace :v1 do 
      resources :articles,      except: [:new, :edit]
      resources :comments,      except: [:new, :edit]
      resources :notifications, only: :index do 
        post :mark_all_read,    on: :collection
      end
      resources :users, only: :index do 
        get :current, on: :collection
      end
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many    :comments, 
              dependent: :destroy, 
              inverse_of: :article
  
  has_many    :notifications,
              inverse_of: :article

  belongs_to  :user, 
              inverse_of: :articles

  validates   :user_id, :text, 
              presence: true

  validates   :title, 
              presence: true,
              length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_many      :notifications,
                dependent: :destroy,
                inverse_of: :comment

  belongs_to    :article, 
                inverse_of: :comments

  belongs_to    :user, 
                inverse_of: :comment

  validates     :user_id, :article, 
                presence: true

  validates     :body, 
                presence: true, 
                length: { minimum: 4}

  after_create :create_notification

  private

  def create_notification
    if (article.user_id != user_id)
      notification = Notification.create!(
        user_id: article.user_id,
        comment_id: id,
        read: false
      )
      UserMailer.delay.comment_create(article.user_id)
    end
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  has_one       :article,
                inverse_of: :notifications,
                through: :comment

  belongs_to    :comment,
                inverse_of: :notifications
  
  belongs_to    :user,
                inverse_of: :notifications

  validates     :user, :comment,
                presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  ADMIN = "admin"
  REGISTERED = "registered"
  has_many :users, inverse_of: :role
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many      :articles, 
                dependent: :destroy, 
                inverse_of: :user

  has_many      :comment, 
                inverse_of: :user

  has_many      :notifications,
                dependent: :destroy,
                inverse_of: :user

  belongs_to    :role, 
                inverse_of: :users

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  before_create :set_default_role

  def is_admin?
    persisted? and role and (role.name == Role::ADMIN) 
  end

  def self.from_omniauth(auth)
    where('(provider = ? and uid = ?) or lower(email) = ?' , auth.provider, auth.uid, auth.info.email.downcase).last || new
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  private
  def set_default_role
    self.role ||= Role.find_by_name(Role::REGISTERED)
  end
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < Api::V1::BaseController

  before_filter :set_user_id, only: :create
  
  private
  def set_user_id
    params[:article][:user_id] = current_user.id
  end
  
  def article_params
    params.require(:article).permit(:title, :text, :user_id)
  end

end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  load_and_authorize_resource

  after_filter :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  def index
    query = resource_klass.accessible_by(current_ability)
    render json: query.where(actual_query)
  end

  def create
    model = resource_klass.new(model_params)
    if model.save
      render json: model
    else
      render json: model.errors, status: 400
    end
  end
 
  def update
    model = resource_klass.find(params[:id])
 
    if model.update(model_params)
      render json: model
    else
      render json: model.errors, status: 400
    end
  end

  def show
    model = resource_klass.find(params[:id])
    render json: model
  end

  def destroy
    model = resource_klass.find(params[:id])
 
    if model.destroy
      render json: model
    else
      render json: model.errors, status: 400
    end
  end

  private 

  def actual_query 
    params[:query] ? JSON.parse(params[:query]) : {}
  end

  protected

  # In Rails 4.2 and above
  def verified_request?
    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::BaseController
  
  before_filter :set_user_id, only: :create
  load_and_authorize_resource
  
  private
  def set_user_id
    params[:comment][:user_id] = current_user.id
  end

  def comment_params
    params.require(:comment).permit(:user_id, :body, :article_id)
  end

end

app/controllers/api/v1/notifications_controller.rb
class Api::V1::NotificationsController < Api::V1::BaseController

  def mark_all_read
    notifications = Notification.where(user_id: current_user.id, read: false)

    notifications.update_all(read: true)

    render json: notifications

  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController

  def current
    render json: current_user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  prepend_before_filter :fix_cancan_params, only: :create

  # from https://github.com/ryanb/cancan/issues/835#issuecomment-20229737
  def fix_cancan_params
    return if devise_controller?
    method = "#{resource_name}_params"
    if respond_to?(method, true)
      params[resource_name] &&= send(method)
    else
      raise "Must define method named #{method} in #{controller_name}."
    end
  end

  protected

  def resource_klass
    resource_name.classify.constantize
  end

  def resource_name
    controller_name.underscore.split('/').last.singularize
  end

  def model_params
    send("#{resource_name}_params")
  end

end

app/controllers/concerns/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.is_admin?
      can :manage, Article, user_id: user.id
      can :manage, Comment
    else
      can [:destroy, :create], Comment, user_id: user.id
    end
    can :read, [Article, Comment]

    if user.persisted?
      can :read, Notification, user_id: user.id
      can :mark_all_read, Notification
      can :current, User
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  skip_load_and_authorize_resource
  
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
end

app/views/articles/_form.html.haml
.starter-template
  = form_for @article do |f|
    - if @article.errors.any?
      #error_explanation
        %h2
          = pluralize(@article.errors.count, "error")
          prohibited
          this article from being saved:
        %ul
          - @article.errors.full_messages.each do |msg|
            %li= msg
    
    %p
      = f.label :title
      %br 
        = f.text_field(:title, class: 'form-control')
    %p
      = f.label :text
      %br
        = f.text_field(:text, class: 'form-control')
    %p
      = f.submit('Submit', class: 'btn btn-success')

app/views/articles/edit.html.haml
.index
  .title
    %h1 Edit article
  = render 'form'
  = link_to 'Back', articles_path

app/views/articles/index.html.haml
.index
  .title
    %h1 Listing Articles 
  -if can? :create, Article
    = link_to 'New article', new_article_path
  %table
    %tr
      %th Title
      %th Text
      %th{colspan: "3"}
    - @articles.each do |article|
      %tr
        %td= article.title
        %td= article.text
        %td= link_to 'Show', article_path(article)
        -if can? :update, article
          %td= link_to 'Edit', edit_article_path(article)
        -if can? :destroy, article
          %td= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }
  - if user_signed_in?
    %td= link_to 'Sign Out', destroy_user_session_path, method: :delete
  - else
    %td= link_to 'Sign In With Facebook', user_omniauth_authorize_path(:facebook)
    %td= link_to 'Sign In', new_user_session_path
    %td= link_to 'Sign Up', new_user_registration_path
  

app/views/articles/new.html.haml
.index
  .title
    %h1 New article
  = render 'form'
  = link_to 'Back', articles_path

app/views/comments/_comment.html.haml
%p
  %strong Commenter:
  = comment.user.email
%p
  %strong Comment:
  = comment.body
%p
  - if can? :destroy, comment
    = link_to 'Destroy Comment', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' }

app/views/comments/_form.html.haml
= form_for([@article, @comment]) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2
        = pluralize(@comment.errors.count, "error")
        prohibited
        this article from being saved:
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg
  
  
  %p
    = f.label :body
    %br 
      = f.text_area(:body, class: 'form-control')
  %p
    = f.submit('Submit', class: 'btn btn-success')
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{'ng-app' => "Blog", 'ng-controller' => 'BaseController'}
    %nav.navbar.navbar-inverse
      .container
        .navbar-header
          %button.navbar-toggle.collapsed
          %a.navbar-brand{href: root_path} Austin's Blog!
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{href: root_path + '#'} Home
            %li
              %a{href: root_path + '#/articles'} Articles
          %ul.nav.navbar-nav.navbar-right{'ng-if' => 'currentUser'}
            %li
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", href: "", role: "button"} 
                {{ currentUser.email }} 
                %span.badge {{ notifications.length }}
                %span.caret{'ng-if' => 'notifications.length > 0'}
              %ul.dropdown-menu{role: "menu", 'ng-if' => 'notifications.length > 0'}
                %li{role: "presentation", 'ng-repeat' => 'notification in notifications'}
                  %a{'ng-blur' => 'markNotificationsAsRead()', 'ng-href' => "#{root_path}#/articles/{{ notification.article_id }}"} {{ notification.display_text }}
    .container
      .div{'ng-view' => ''}
      = yield

app/views/layouts/comment_create.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %body
    %h1
      Hey, #{@user.email}!
    %p
      Someone seems to have commented on your article! Come check it out.
      %br

app/views/layouts/comment_created.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %body
    %h1
      Hey, #{@user.email}!
    %p
      Someone seems to have commented on your article! Come check it out.
      %br

app/views/layouts/welcome_email.html.haml
Welcome to my blog, #{@user.email}!
===============================================
 
You have successfully signed up to my blog,
your username is: #{@user.email}.
 
To login to the site, just follow this link: #{ @url }.
 
Thanks for joining and have a great day!

app/views/notifications/_notification.html.haml
%p
  = link_to "", notification_path(notification.id), method: :delete, class: "glyphicon glyphicon-remove"
%hr/

app/views/notifications/index.html.haml
%h1 Notifications
- if @notifications.present?
  = render partial: "notifications/notification", collection: @notifications
- else
  %p No notifications!

= link_to 'Back to Articles', articles_path